In [35]:
import pandas as pd
import numpy as np
pd.__version__

'1.2.1'

In [36]:
!pip install pandas=='0.25.3'

  Using cached pandas-0.25.3-cp37-cp37m-manylinux1_x86_64.whl (10.4 MB)
  Attempting uninstall: pandas
    Found existing installation: pandas 1.2.1
    Uninstalling pandas-1.2.1:
      Successfully uninstalled pandas-1.2.1


In [42]:
time_series_data = pd.Series([-4801437.19, 1761188.96, -270300.70999999996, -4178163.7100000004, 4632051.969999999, -5393208.649999999, 2760529.67, -605301.4799999995, 6734722.98, -8489289.790000001, -1354712.4900000002, 1119246.08, 5779055.780000001, -1029468.9600000009, 545920.9900000002, -2535959.6399999997, -160174.4400000004, -2419089.68, 3123979.57, 5516368.340000001, -5306687.28, 4233416.04, -3643162.9000000004, -1614264.71, 249987.98000000045, -2115163.0800000005, 10006138.940000001, -7530486.950000001, -2886445.2199999997, 656409.9900000002, 985029.4100000001, 688501.96, -3461456.43, 1063632.58, 6126332.859999999, -16725.179999999702, -1474098.08, -883147.6200000001, -3943669.89, 4752597.0, -1082448.7400000002, -4483958.37, 5842732.85, -290000.5599999996, -3788354.3200000003, 4173927.7300000004, -1504901.62, -1537969.83, 1123939.0499999998, 1496232.33, -1269915.9399999995, -2519750.0700000003, 7942998.859999999, -6714138.869999999, 549395.29, 639529.0499999998, -2206370.7800000003, 854682.1399999997, 5444558.3100000005, -5464422.07, -992120.8599999994, -711968.1900000004, 5361700.069999999, 1883912.6600000001, -4785280.72, -2733929.3899999997, 6619948.1899999995, -4853274.399999999, 680019.5300000003, 3607724.6999999993, -5002636.39, 341343.9799999995, 783869.6200000001, 6937342.510000001, -6280630.79, -1025991.25, 1159082.8899999997, 2114741.05, -5351795.24, 3288481.9999999995, -38557.87999999989, -3074268.4999999995, 2409442.52, -1300259.9300000006, 598342.9600000009, 505362.1199999992, -1525466.6499999994, 6343042.4799999995, -7390705.449999999, 3463364.4])

In [52]:
moving_avg = time_series_data.ewm(span=10).mean()
moving_std = time_series_data.ewm(span=10).std()
print(list(map(float, moving_avg.values[:90])))
moving_std

[-4801437.19, -1191992.8074999999, -821478.7085049833, -1927356.8612252478, -44328.985341072104, -1433617.794283731, -422996.7383469379, -464471.94564925705, 1101820.939622015, -912850.9982443772, -1003117.7768834172, -579073.3626350361, 668831.8820968807, 340255.92174894613, 379588.20777020464, -172787.10548015177, -170415.6475210844, -590608.942344259, 100025.17163665044, 1102939.0928370436, -79937.35468602793, 713912.3247032989, -86202.6818429657, -366300.467441823, -253500.62069164187, -593829.6961933856, 1342023.8598455505, -277035.600287305, -752886.6275706189, -496026.8700029551, -226207.59799688548, -59625.86131235196, -678964.5959893074, -361783.4419754448, 818925.7551779589, 666878.4131544861, 277377.71198230545, 66270.11566331188, -663101.018556033, 321893.0303190392, 66489.91828024178, -761045.2328244478, 439856.4990601735, 307135.79193970223, -437587.94767099543, 400951.59976333485, 54405.05438387266, -235136.64089327017, 11981.290243118268, 281856.96392376395, -293.699024

0              NaN
1     4.640477e+06
2     3.162399e+06
3     3.058619e+06
4     4.183506e+06
          ...     
85    2.622647e+06
86    2.453596e+06
87    3.484617e+06
88    4.625672e+06
89    4.495031e+06
Length: 90, dtype: float64

In [16]:
len(moving_avg)

19

In [64]:
# Ignore the first observation while identifying outliers
# Moving average at time t considers the data till t and is the predicted value at (t+1)
is_outlier = np.zeros(90)
temp = np.abs(time_series_data.values[1:90] - moving_avg.values[0:-1])/moving_std.values[0:-1]
temp

array([       nan, 0.1986201 , 1.06143622, 2.14456573, 1.27856378,
       0.9563564 , 0.04286154, 1.94228371, 2.09976443, 0.07590038,
       0.40990729, 1.35096555, 0.34008648, 0.04536828, 0.71598889,
       0.00327028, 0.64761384, 1.13832118, 1.63376032, 1.72007669,
       1.01086688, 1.02811686, 0.36194399, 0.15944541, 0.53158967,
       3.25641917, 1.69769663, 0.43866928, 0.2570608 , 0.29678049,
       0.20090935, 0.82287458, 0.43710604, 1.76568336, 0.19691602,
       0.55563577, 0.32306927, 1.2213747 , 1.59859721, 0.37216324,
       1.31495583, 1.81620616, 0.17190508, 1.06328029, 1.19424163,
       0.48076625, 0.43406899, 0.4019975 , 0.47762708, 0.539763  ,
       0.94154202, 3.19658201, 1.87028437, 0.18207919, 0.18434345,
       0.53637942, 0.34049582, 1.63525948, 1.62578909, 0.15625964,
       0.06976406, 1.64334564, 0.32676672, 1.53011383, 0.62973223,
       1.92885169, 1.2195703 , 0.21920911, 0.88805585, 1.3397693 ,
       0.18787645, 0.28118164, 1.95812885, 1.7112793 , 0.16762

In [66]:
is_outlier[1:] = (temp>2).astype(int)
print(is_outlier)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]


In [59]:
is_outlier[1:] = (temp > 2).astype(int)

In [68]:
# Locations of predicted outliers
np.where(is_outlier == 1)[0]

array([ 4,  9, 26, 52, 87, 88])

In [7]:
# Locations of true outliers
np.where(time_series_data != 1)[0]

array([11, 15, 18])